spring.application.name=game-store

spring.datasource.url=jdbc:postgresql://localhost:5432/game-store
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true